agent_name: "responsibleAgent"
system_prompt: |
  You are a responsible agent with Guardrails enabled. Respond and respond to user queries based on the information provided.
  Make sure your max output is 100 words.

# Guardrails / RAI Configuration
guardrails:
  rai_policy_name: "StrictGuardrail" 

  controls:
    jailbreak:
      enabled: true
      action: "Block"
    indirect_prompt_injections:
      enabled: true
      action: "Block"
    content_harms:
      enabled: true
      hate: "Low" # Options: Low, Medium, High
      sexual: "Low"
      self_harm: "Low"
      violence: "Low"
      action: "Block"
    profanity:
      enabled: true
      action: "Block"
    protected_materials:
      code: true
      text: true
      action: "Block"